### ISSUE TITLE
widget problem

### ISSUE THREAD

**Issue by seema84** [f1rehead/SlideshowSE#2]
this commit break my widget design
https://github.com/f1rehead/SlideshowSE/commit/3efa50f3b2a74d986a18d0f860f0d37ab7379455

**Comment by seema84** [comment]
it is the same problem as I have addressed here (there is also a solution)
https://github.com/Asgaros/asgaros-forum/issues/359

**Comment by f1rehead** [comment]
I’ll take a look. The changes were mandated by the Wordpress plugin team after a security audit, so they can’t be removed. I’ll try to find some way to fix it. On Mar 15, 2023, at 09:20, seema84 ***@***.***> wrote:﻿
it is the same problem as I have addressed here (there is also a solution)
Asgaros/asgaros-forum#359

**Comment by seema84** [comment]
Is there any progress yet?

**Comment by f1rehead** [comment]
I checked in a fix, I think. I don't use widgets and haven't replicated your issue. Try it and let me know.

**Comment by seema84** [comment]
this commit https://github.com/f1rehead/SlideshowSE/commit/9fb9d08b753644a508f078d96a66d58ecf624403 does not work
the sildeshow is not loaded/displayed in the widget

**Comment by f1rehead** [comment]
I'm kind of stumped. I've been playing with it and I can't get the widget to work at all, in any 6.x version of Wordpress. What happens if you use the SlideshowSEPluginWidget.php file from before the https://github.com/f1rehead/SlideshowSE/commit/3efa50f3b2a74d986a18d0f860f0d37ab7379455 commit?

**Comment by seema84** [comment]
Before commit 3efa50f my widgets work without problems.

**Comment by f1rehead** [comment]
Maybe I need some clarification - when you say "my widgets" what do you mean? The SlideshowSE widget you have used on your site, or every widget you are using on your site including the ones that are not SlideshowSE widgets?

**Comment by seema84** [comment]
I mean the "SlideshowSE widget". I use only one of them.

**Comment by f1rehead** [comment]
I’ve spent a lot of time looking at this and I can’t figure it out. The theme I use doesn’t have a space for widgets, so I activated the Twenty Twenty theme to try to see the error. The Slideshow SE widget works in that theme.

What error message do you get? Can you change to the Twenty Twenty theme and see if it works for you in that theme?

**Comment by seema84** [comment]
The Twenty Twenty theme does not have the display problem. But it is also structured quite differently. 

Before commit 3efa50f

![12](https://user-images.githubusercontent.com/2832339/233959284-9f7af050-625e-4131-9064-63972e4fbf7c.PNG)
![12q](https://user-images.githubusercontent.com/2832339/233959296-978e0e54-3160-4889-90d2-1558e578db33.PNG)

Before commit 9fb9d08

![13](https://user-images.githubusercontent.com/2832339/233959486-114203ec-37c9-4eab-bc10-fb2a9bb51a0f.PNG)
![13q](https://user-images.githubusercontent.com/2832339/233959504-ddb9e48d-9ba4-4c06-848a-3cdebda43d0f.PNG)

Maybe you can look at the problem again at asgaros-forum (which I linked), it was fixed there.

**Comment by f1rehead** [comment]
Well i made those changes and you said it didn’t work, so I’m at a loss.

**Comment by seema84** [comment]
exactly, in commit 9fb9d08 it looks like this

![14](https://user-images.githubusercontent.com/2832339/234232461-593b285e-7288-4b8f-9bb4-4f1f24cbce67.PNG)
![14q](https://user-images.githubusercontent.com/2832339/234232467-6fe2b71f-dd72-4160-9619-3d204e3d47fd.PNG)

**Comment by f1rehead** [comment]
It should be fixed now. Sorry about the delay. I had an issue in the database that was masking the problem. Once I dug down far enough to see the database problem, it was a simple fix. Let me know if that works for you and I'll put out another version on the WP Plugin site.

**Comment by f1rehead** [comment]
If you knew the issue was a misplaced parenthesis, a PR would have been preferable to me spending many hours chasing down an issue I was not able to replicate. On Apr 27, 2023, at 17:40, seema84 ***@***.***> wrote:﻿
Commit fdf480b works.
It also includes again the line as before 3efa50f . With it I had it temporarily also fixed.
// Output widget
echo $beforeWidget . (!empty($title) ? $beforeTitle . $title . $afterTitle : '') . $output . $afterWidget;

**Comment by seema84** [comment]
I didn't know about the parenthesis.

I have this line 

echo $beforeWidget . (!empty($title) ? $beforeTitle . $title . $afterTitle : '' . wp_kses_post($output) . $afterWidget);

simply changed to this 

echo $beforeWidget . (!empty($title) ? $beforeTitle . $title . $afterTitle : '') . $output . $afterWidget;

as it was before 3efa50f. I had not touched the rest.

**Comment by seema84** [comment]
Thank you for fixing the problem. <3
